//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSULTAS
    {
        public int ID { get; set; }
        public int NUMERO_SEMANA { get; set; }
        public int CANTIDAD_ESTUDIANTE { get; set; }
        public string TIPO_CONSULTA { get; set; }
        public string TEMA_CONSULTA { get; set; }
        public System.DateTime FECHA { get; set; }
        public string CARNET_ESTUDIANTE { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<bool> APROBACION { get; set; }
    }
}
